---
- name: Configure web server
  hosts: web
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes
